In [1]:
array=[90,80,40,30]
print(array)

[90, 80, 40, 30]


In [5]:
import numpy as np
arr =np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [19]:
print(arr[2])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [13]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [23]:
import numpy as np
arr =np.array([1,2,3,4,5])
print(arr[2])

3


In [27]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print (arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,4])

10


In [47]:
import numpy as np
arr=np.array([[[1,2,3,],[5,6,7,]],[[9,10,11,],[12,13,14]]])
print(arr[0,1,2,])

7


In [52]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[0:5])

[1 2 3 4 5]


In [58]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [63]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
newarr=arr.reshape(6,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [65]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
newarr=arr.reshape(2,3,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
